language: node_js
node_js:
  - "0.8"
  - "0.10"
before_script:
  - sudo apt-get install fontforge eot-utils
  - wget http://people.mozilla.com/~jkew/woff/woff-code-latest.zip
  - unzip woff-code-latest.zip -d sfnt2woff && cd sfnt2woff && make && sudo mv sfnt2woff /usr/local/bin/ && cd ..
  - npm install -g grunt-cli
